services:
  php81:
    container_name: laravel-love-lib-81
    image: laravel-love-lib-81
    build:
      context: ./
      dockerfile: ./.docker/php.Dockerfile
      args:
        PHP_VERSION: "8.1"
    tty: true
    working_dir: /app
    volumes:
      - ./:/app

  php82:
    container_name: laravel-love-lib-82
    image: laravel-love-lib-82
    build:
      context: ./
      dockerfile: ./.docker/php.Dockerfile
      args:
        PHP_VERSION: "8.2"
    tty: true
    working_dir: /app
    volumes:
      - ./:/app

  php83:
    container_name: laravel-love-lib-83
    image: laravel-love-lib-83
    build:
      context: ./
      dockerfile: ./.docker/php.Dockerfile
      args:
        PHP_VERSION: "8.3"
    tty: true
    working_dir: /app
    volumes:
      - ./:/app

  php84:
    container_name: laravel-love-lib-84
    image: laravel-love-lib-84
    build:
      context: ./
      dockerfile: ./.docker/php.Dockerfile
      args:
        PHP_VERSION: "8.4"
    tty: true
    working_dir: /app
    volumes:
      - ./:/app

  php85:
    container_name: laravel-love-lib-85
    image: laravel-love-lib-85
    build:
      context: ./
      dockerfile: ./.docker/php.Dockerfile
      args:
        PHP_VERSION: "8.5"
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
